name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: 'public'
          aws-region: us-east-2

      - name: Build, tag, and push Docker image
        env:
          PUBLIC_ECR_REPO_URI: ${{ secrets.PUBLIC_ECR_REPO_URI }}
        run: |
          docker build -t $PUBLIC_ECR_REPO_URI:latest .
          docker push $PUBLIC_ECR_REPO_URI:latest

      - name: Verify image pushed to ECR
        run: |
          echo "Docker image has been pushed to: ${{ secrets.PUBLIC_ECR_REPO_URI }}"
